-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 15:09:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gauth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gauth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gauth` DEFAULT CHARACTER SET utf8 ;
USE `gauth` ;

-- -----------------------------------------------------
-- Table `gauth`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gauth`.`User` (
  `user_code` INT(11) NOT NULL,
  `user_id` NVARCHAR(50) NOT NULL,
  `password` NVARCHAR(200) NOT NULL,
  `email` NVARCHAR(50) NULL,
  `nikname` NVARCHAR(20) NULL,
  `register_date` DATETIME NULL,
  `phone` NVARCHAR(15) NULL,
  `address` NVARCHAR(300) NULL,
  `company` NVARCHAR(20) NULL,
  PRIMARY KEY (`user_code`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gauth`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gauth`.`Client` (
  `client_id` NVARCHAR(20) NOT NULL,
  `client_secret` NVARCHAR(40) NULL,
  `description` NVARCHAR(100) NULL,
  `domain` NVARCHAR(100) NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gauth`.`Scope`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gauth`.`Scope` (
  `scope_id` NVARCHAR(50) NOT NULL,
  `client_id` NVARCHAR(20) NOT NULL,
  `description` NVARCHAR(100) NULL COMMENT '클라이언트 권한',
  `is_default` TINYINT NULL,
  PRIMARY KEY (`scope_id`, `client_id`),
  INDEX `fk_Scope_Client_idx` (`client_id` ASC),
  CONSTRAINT `fk_Scope_Client`
    FOREIGN KEY (`client_id`)
    REFERENCES `gauth`.`Client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gauth`.`UserClientScope`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gauth`.`UserClientScope` (
  `id` INT(11) NOT NULL,
  `client_id` NVARCHAR(20) NOT NULL COMMENT '처음 로그인시 등록되는 권한맵핑',
  `scope_id` NVARCHAR(50) NOT NULL,
  INDEX `fk_UserClientScope_Scope1_idx` (`scope_id` ASC, `client_id` ASC),
  INDEX `fk_UserClientScope_User1_idx` (`id` ASC),
  CONSTRAINT `fk_UserClientScope_Scope`
    FOREIGN KEY (`scope_id` , `client_id`)
    REFERENCES `gauth`.`Scope` (`scope_id` , `client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserClientScope_User1`
    FOREIGN KEY (`id`)
    REFERENCES `gauth`.`User` (`user_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gauth`.`Token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gauth`.`Token` (
  `token_id` VARCHAR(50) NOT NULL,
  `id` INT(11) NOT NULL,
  `client_id` NVARCHAR(20) NOT NULL,
  `create_time` DATETIME NULL,
  `expire_date` DATETIME NULL,
  PRIMARY KEY (`token_id`),
  INDEX `fk_token_Client1_idx` (`client_id` ASC),
  INDEX `fk_Token_User1_idx` (`id` ASC),
  CONSTRAINT `fk_token_Client`
    FOREIGN KEY (`client_id`)
    REFERENCES `gauth`.`Client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Token_User`
    FOREIGN KEY (`id`)
    REFERENCES `gauth`.`User` (`user_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gauth`.`Pending`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gauth`.`Pending` (
  `email` VARCHAR(50) NOT NULL,
  `activate_key` VARCHAR(40) NULL,
  `status` VARCHAR(20) NULL,
  `expire_date` DATETIME NULL,
  `client_id` VARCHAR(20) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
